version: '3.8'
services:
  api:
    image: "node:16-bullseye"
    volumes:
      - $PWD/api:/usr/src/app
    networks:
      - recipes_network
    ports:
      - 3000:$API_PORT
      - "9229:9229"
    init: true
    working_dir: "/usr/src/app"
    depends_on:
      - "elasticsearch"
    command: "npm run start"
    deploy:
      restart_policy:
        delay: "5s"
        max_attempts: 5

  elasticsearch:
    image: "elasticsearch:7.14.2"
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
    volumes:
     - data01:/usr/share/elasticsearch/data
    networks:
     - recipes_network
  kibana:
    image: "kibana:7.14.2"
    ports:
     - "5601:5601"
    networks:
     - recipes_network
volumes:
  data01:
networks:
  recipes_network:
